#Project key ahs to be the same as the one in pom "  <sonar_projectKey>org.example:week4-swp2-cw</sonar_projectKey>"
sonar.projectKey= org.example:week1-swp2
sonar.projectName=Shopping Cart GUI
sonar.projectVersion=2.0-SNAPSHOT
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.host.url=http://localhost:9000
# If you add the token in user variable in Edit System Environment you donot need to mention
#sonar.token= squ_36ddcb7129eea21de9e6ef95dd0081b14220ecce
# run with:
#    mvn clean verify sonar:sonar "-Dsonar.projectKey=avgspd" "-Dsonar.token=$env:SONAR_TOKEN" "-Dsonar.host.url=http://localhost:9000"
